name: Build Herbie Binaries in Odyssey

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - '*'
jobs:
  build-herbie:
    name: Build Herbie Binaries
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            os-name: linux
            arch: x64
          - os: macos-latest
            os-name: macos
            arch: x64
          - os: windows-latest
            os-name: windows
            arch: x64

    runs-on: ${{ matrix.os }}

    steps:
      # Checkout Odyssey repository
      - name: Checkout Odyssey repository
        uses: actions/checkout@v4

      # Clone Herbie repository inside Odyssey
      - name: Clone Herbie repository
        run: git clone https://github.com/herbie-fp/herbie.git

      # Install Racket (Required for Herbie)
      - name: Install Racket
        uses: Bogdanp/setup-racket@v1.11
        with:
          version: 8.11
          architecture: ${{ matrix.arch }}

      # Install Rust Compiler (For egg-herbie)
      - name: Install Rust compiler
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Build Herbie
        run: |
          cd herbie
          make install
      
      - name: Check Installed Herbie Binary
        run: which herbie
      
      - name: List Installed Racket Packages
        run: raco pkg show
      
      - name: Check Herbie Collects Directory
        run: ls -R /home/runner/.local/share/racket/8.11/collects/

      - name: Find Herbie in Other Paths
        run: |
          echo "Checking alternative paths..."
          ls -R /usr/share/racket/collects/ || echo "Not found in /usr/share/racket/collects"
          ls -R /home/runner/.racket/collects/ || echo "Not found in /home/runner/.racket/collects"
          ls -R /home/runner/.local/share/racket/collects/ || echo "Not found in /home/runner/.local/share/racket/collects"
      - name: Package Herbie for Distribution
        run: |
            mkdir -p herbie-package/bin
            cp /home/runner/.local/share/racket/8.11/bin/herbie herbie-package/bin/
            cp -r /home/runner/.local/share/racket/8.11/collects/herbie herbie-package/herbie-collects/
            cp -r /home/runner/.local/share/racket/8.11/lib herbie-package/racket-lib/
            tar -czvf herbie-${{ matrix.os-name }}.tar.gz -C herbie-package .
            
      - name: Upload Packaged Herbie
        uses: actions/upload-artifact@v4
        with:
            path: herbie-${{ matrix.os-name }}.tar.gz
            name: herbie-package-${{ matrix.os-name }}.tar.gz
            if-no-files-found: error


      # Upload Herbie Binary to Odyssey Artifacts
      - name: Upload Herbie Package to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: herbie-${{ matrix.os-name }}.tar.gz
          asset_name: herbie-${{ matrix.os-name }}.tar.gz
          tag: ${{ github.ref }}